baseurl:
title: Yufei Zhao
url: https://yufeizhao.com
description:
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: pretty
timezone: America/New_York
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md', 'cv.tex']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: emacs
git:
  branch: master

kramdown:
  auto_ids: true
